#!/bin/bash
SERVER="127.0.0.1:2019"
gnome-terminal -e "php -S $SERVER -t $(pwd)/www"
[ $? = 0 ] && echo "Dev server is online"

python3 << EOF
import webbrowser
webbrowser.open_new_tab("http://localhost:2019")
EOF
