#!/bin/bash
SERVER="127.0.0.1:2019"
dev=( $(ps aux | grep $SERVER) )

kill "${dev[1]}" 2> /dev/null
if [ "$?" = "0" ]; then
  echo "Dev server terminated"
else
  echo "Dev server is already inactive"
fi
