#!/bin/bash
# Use --dry-run to disable git features

OUTPUT=".build"
./run/cairn www "$OUTPUT"
cd www
php 404.php > "../$OUTPUT/404.html"
cd ..

if [ "$1" = "--dry-run" ]; then
    exit 0
fi

cd "$OUTPUT"
git init
git remote add origin https://github.com/alugocp/lugocorp.git
git add .
git commit -m "Upload on $(date)"
git push -f origin master:gh-pages
cd ..
rm -rf "$OUTPUT"
